defmodule Datos do
  @moduledoc """
    Datos base del sistema.
    Provee las tres colecciones principales del sistema:
    confeccionistas, líneas y lotes.
  """
  def confeccionistas do
    [
    %{codigo: "C01", nombre: "María Elena Ríos", alquiler: true},
    %{codigo: "C02", nombre: "Andrés Salazar", alquiler: false},
    %{codigo: "C03", nombre: "Luisa Fernanda Gómez", alquiler: true},
    %{codigo: "C04", nombre: "Carlos Pérez", alquiler: true},
    %{codigo: "C05", nombre: "Ana Torres", alquiler: false},
    %{codigo: "C06", nombre: "Jorge Ramírez", alquiler: false},
    %{codigo: "C07", nombre: "Paula Herrera", alquiler: true},
    %{codigo: "C08", nombre: "Diego Castro", alquiler: false},
    %{codigo: "C09", nombre: "Sofía Londoño", alquiler: false},
    %{codigo: "C10", nombre: "Mateo Vargas", alquiler: true},
    %{codigo: "C11", nombre: "Camila Osorio", alquiler: false},
    %{codigo: "C12", nombre: "Felipe Cardona", alquiler: false}
    ]
  end

  def lineas do
    [
    %{id: "L1", nombre: "Línea Norte", puestos: 6},
    %{id: "L2", nombre: "Línea Central", puestos: 4},
    %{id: "L3", nombre: "Línea Sur", puestos: 5},
    %{id: "L4", nombre: "Línea Este", puestos: 2}
    ]
  end

  def lotes do
    [
    %{confeccionista: "C06", linea: "L2", dia: 4, prendas: 106, defectos: 3},
    %{confeccionista: "C01", linea: "L1", dia: 1, prendas: 126, defectos: 6},
    %{confeccionista: "C01", linea: "L2", dia: 3, prendas: 122, defectos: 10},
    %{confeccionista: "C01", linea: "L2", dia: 6, prendas: 59, defectos: 2},
    %{confeccionista: "C12", linea: "L3", dia: 6, prendas: 132, defectos: 14},
    %{confeccionista: "C04", linea: "L2", dia: 1, prendas: 181, defectos: 1},
    %{confeccionista: "C10", linea: "L4", dia: 6, prendas: 143, defectos: 2},
    %{confeccionista: "C05", linea: "L4", dia: 4, prendas: 56, defectos: 10},
    %{confeccionista: "C02", linea: "L1", dia: 4, prendas: 139, defectos: 8},
    %{confeccionista: "C11", linea: "L2", dia: 3, prendas: 18, defectos: 8},
    %{confeccionista: "C10", linea: "L1", dia: 1, prendas: 144, defectos: 3},
    %{confeccionista: "C09", linea: "L1", dia: 1, prendas: 30, defectos: 11},
    %{confeccionista: "C06", linea: "L2", dia: 1, prendas: 116, defectos: 14},
    %{confeccionista: "C03", linea: "L4", dia: 6, prendas: 64, defectos: 3},
    %{confeccionista: "C09", linea: "L2", dia: 6, prendas: 149, defectos: 10},
    %{confeccionista: "C10", linea: "L2", dia: 1, prendas: 110, defectos: 1.5},
    %{confeccionista: "C01", linea: "L3", dia: 6, prendas: 69, defectos: 4},
    %{confeccionista: "C09", linea: "L2", dia: 6, prendas: 98, defectos: 4},
    %{confeccionista: "C02", linea: "L2", dia: 0, prendas: 50, defectos: 1},
    %{confeccionista: "C02", linea: "L2", dia: 5, prendas: 58, defectos: 2},
    %{confeccionista: "C08", linea: "L1", dia: 6, prendas: 30, defectos: 5},
    %{confeccionista: "C01", linea: "L1", dia: 7, prendas: 50, defectos: 1},
    %{confeccionista: "C04", linea: "L4", dia: 3, prendas: 56, defectos: 1.5},
    %{confeccionista: "C08", linea: "L4", dia: 1, prendas: 107, defectos: 4},
    %{confeccionista: "C06", linea: "L3", dia: 3, prendas: 47, defectos: 18},
    %{confeccionista: "C05", linea: "L3", dia: 4, prendas: 108, defectos: 8},
    %{confeccionista: "C07", linea: "L2", dia: 1, prendas: 45, defectos: 11},
    %{confeccionista: "C07", linea: "L1", dia: 3, prendas: 63, defectos: 1.5},
    %{confeccionista: "C06", linea: "L1", dia: 3, prendas: 41, defectos: 0.5},
    %{confeccionista: "C01", linea: "L2", dia: 4, prendas: 150, defectos: 5},
    %{confeccionista: "C10", linea: "L2", dia: 3, prendas: 40, defectos: 5},
    %{confeccionista: "C91", linea: "L2", dia: 2, prendas: 50, defectos: 1},
    %{confeccionista: "C06", linea: "L4", dia: 2, prendas: 88, defectos: 11},
    %{confeccionista: "C01", linea: "L1", dia: 6, prendas: 144, defectos: 8},
    %{confeccionista: "C11", linea: "L1", dia: 1, prendas: 116, defectos: 0.5},
    %{confeccionista: "C04", linea: "L2", dia: 1, prendas: 77, defectos: 1.5},
    %{confeccionista: "C04", linea: "L1", dia: 1, prendas: 49, defectos: 4},
    %{confeccionista: "C02", linea: "L2", dia: 1, prendas: 38, defectos: 10},
    %{confeccionista: "C08", linea: "L3", dia: 5, prendas: 64, defectos: 18},
    %{confeccionista: "C09", linea: "L2", dia: 5, prendas: 20, defectos: 0.5},
    %{confeccionista: "C09", linea: "L4", dia: 3, prendas: 116, defectos: 6},
    %{confeccionista: "C01", linea: "L90", dia: 1, prendas: 50, defectos: 1},
    %{confeccionista: "C08", linea: "L4", dia: 4, prendas: 94, defectos: 1.5},
    %{confeccionista: "C12", linea: "L3", dia: 2, prendas: 129, defectos: 4},
    %{confeccionista: "C12", linea: "L2", dia: 5, prendas: 137, defectos: 2},
    %{confeccionista: "C02", linea: "L91", dia: 2, prendas: 50, defectos: 1},
    %{confeccionista: "C03", linea: "L1", dia: 1, prendas: 0, defectos: 1},
    %{confeccionista: "C07", linea: "L4", dia: 2, prendas: 35, defectos: 2},
    %{confeccionista: "C10", linea: "L2", dia: 3, prendas: 82, defectos: 4},
    %{confeccionista: "C04", linea: "L2", dia: 4, prendas: 147, defectos: 8},
    %{confeccionista: "C01", linea: "L1", dia: 1, prendas: 39, defectos: 5},
    %{confeccionista: "C11", linea: "L1", dia: 2, prendas: 30, defectos: 18},
    %{confeccionista: "C12", linea: "L1", dia: 5, prendas: 149, defectos: 18},
    %{confeccionista: "C07", linea: "L1", dia: 1, prendas: 46, defectos: 3},
    %{confeccionista: "C02", linea: "L2", dia: 5, prendas: 135, defectos: 3},
    %{confeccionista: "C02", linea: "L3", dia: 2, prendas: 136, defectos: 18},
    %{confeccionista: "C05", linea: "L1", dia: 1, prendas: 50, defectos: 101},
    %{confeccionista: "C08", linea: "L3", dia: 2, prendas: 58, defectos: 11},
    %{confeccionista: "C06", linea: "L4", dia: 2, prendas: 131, defectos: 1.5},
    %{confeccionista: "C90", linea: "L1", dia: 1, prendas: 50, defectos: 1},
    %{confeccionista: "C03", linea: "L4", dia: 5, prendas: 104, defectos: 2},
    %{confeccionista: "C09", linea: "L4", dia: 6, prendas: 48, defectos: 0.5},
    %{confeccionista: "C10", linea: "L1", dia: 4, prendas: 33, defectos: 3},
    %{confeccionista: "C06", linea: "L2", dia: 1, prendas: 50, defectos: -1},
    %{confeccionista: "C07", linea: "L4", dia: 5, prendas: 117, defectos: 18},
    %{confeccionista: "C10", linea: "L3", dia: 2, prendas: 102, defectos: 18},
    %{confeccionista: "C06", linea: "L3", dia: 5, prendas: 35, defectos: 3},
    %{confeccionista: "C11", linea: "L4", dia: 6, prendas: 42, defectos: 10},
    %{confeccionista: "C04", linea: "L4", dia: 1, prendas: 124, defectos: 5},
    %{confeccionista: "C05", linea: "L2", dia: 2, prendas: 78, defectos: 6},
    %{confeccionista: "C06", linea: "L1", dia: 4, prendas: 22, defectos: 4},
    %{confeccionista: "C09", linea: "L1", dia: 6, prendas: 31, defectos: 8},
    %{confeccionista: "C11", linea: "L4", dia: 3, prendas: 74, defectos: 2},
    %{confeccionista: "C03", linea: "L3", dia: 2, prendas: 53, defectos: 8},
    %{confeccionista: "C10", linea: "L4", dia: 4, prendas: 53, defectos: 14},
    %{confeccionista: "C07", linea: "L1", dia: 2, prendas: 34, defectos: 10},
    %{confeccionista: "C01", linea: "L2", dia: 6, prendas: 63, defectos: 4},
    %{confeccionista: "C09", linea: "L1", dia: 3, prendas: 131, defectos: 14},
    %{confeccionista: "C02", linea: "L4", dia: 2, prendas: 30, defectos: 3},
    %{confeccionista: "C01", linea: "L4", dia: 6, prendas: 61, defectos: 11},
    %{confeccionista: "C11", linea: "L1", dia: 4, prendas: 81, defectos: 10},
    %{confeccionista: "C08", linea: "L4", dia: 3, prendas: 86, defectos: 2},
    %{confeccionista: "C05", linea: "L2", dia: 1, prendas: 41, defectos: 11},
    %{confeccionista: "C07", linea: "L1", dia: 3, prendas: 138, defectos: 14},
    %{confeccionista: "C09", linea: "L3", dia: 4, prendas: 72, defectos: 11},
    %{confeccionista: "C03", linea: "L1", dia: 4, prendas: 102, defectos: 18},
    %{confeccionista: "C10", linea: "L3", dia: 2, prendas: 149, defectos: 8},
    %{confeccionista: "C03", linea: "L1", dia: 4, prendas: 150, defectos: 4},
    %{confeccionista: "C02", linea: "L1", dia: 2, prendas: 146, defectos: 6},
    %{confeccionista: "C04", linea: "L2", dia: 4, prendas: 117, defectos: 18},
    %{confeccionista: "C12", linea: "L4", dia: 2, prendas: 103, defectos: 0.5},
    %{confeccionista: "C01", linea: "L2", dia: 5, prendas: 134, defectos: 14},
    %{confeccionista: "C02", linea: "L2", dia: 3, prendas: 53, defectos: 3},
    %{confeccionista: "C06", linea: "L1", dia: 5, prendas: 45, defectos: 6},
    %{confeccionista: "C06", linea: "L2", dia: 6, prendas: 85, defectos: 8},
    %{confeccionista: "C07", linea: "L3", dia: 3, prendas: 121, defectos: 5},
    %{confeccionista: "C06", linea: "L2", dia: 5, prendas: 138, defectos: 11},
    %{confeccionista: "C10", linea: "L3", dia: 5, prendas: 129, defectos: 18},
    %{confeccionista: "C07", linea: "L3", dia: 5, prendas: 37, defectos: 18},
    %{confeccionista: "C10", linea: "L1", dia: 5, prendas: 137, defectos: 14}
    ]
  end

end
